pool:
  vmImage: 'ubuntu-latest'

steps:

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'export GIT_VERSION=$(git describe); export Build.BuildNumber=$GIT_VERSION'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'
    arguments: '-c Release /p:AssemblyVersion=$(GIT_VERSION) /p:Version=$(GIT_VERSION)'

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: 'test'

- task: DotNetCoreCLI@2
  displayName: Pack
  inputs:
    command: 'pack'
    packagesToPack: '**/Kuvalda.Core.csproj'
    nobuild: true
    versioningScheme: 'off'

- task: PublishBuildArtifacts@1
  displayName: Publish artifacts
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'Kuvalda.Core'
    publishLocation: 'Container'